# Generated by Django 3.2.9 on 2021-11-13 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='city',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Город')),
            ],
        ),
        migrations.CreateModel(
            name='street',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shops.city')),
            ],
        ),
        migrations.CreateModel(
            name='shops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.TextField(verbose_name='Дом')),
                ('street', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shops.street')),
            ],
        ),
    ]
