# Generated by Django 3.2.9 on 2021-11-13 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_street_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='shops',
            name='name',
            field=models.CharField(default='null', max_length=150, verbose_name='Магазин'),
        ),
    ]
