# Generated by Django 3.2.9 on 2021-11-13 13:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_shops_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='shops',
            name='closing_time',
            field=models.TimeField(default=datetime.datetime(2021, 11, 13, 13, 56, 50, 446178), verbose_name='Время закрытия'),
        ),
        migrations.AddField(
            model_name='shops',
            name='opening_time',
            field=models.TimeField(default=datetime.datetime(2021, 11, 13, 13, 56, 50, 446160), verbose_name='Время открытия'),
        ),
    ]
